from collections.abc import Mapping
from typing import Any

MODEL_CHOICES = ("gpt-3.5-turbo", "gpt-4", "gpt-4-turbo-preview")
DEFAULT_MODEL = "gpt-3.5-turbo"
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.5
DEFAULT_TEMPERATURE = 0.7
MIN_FREQUENCY_PENALTY = -2.0
MAX_FREQUENCY_PENALTY = 2.0
DEFAULT_FREQUENCY_PENALTY = 0.0
MIN_PRESENCE_PENALTY = -2.0
MAX_PRESENCE_PENALTY = 2.0
DEFAULT_PRESENCE_PENALTY = 0.0
MIN_TOP_P = 0.0
MAX_TOP_P = 1.0
DEFAULT_TOP_P = 0.7

CHROMADB_CHUNK_SIZE = 300
CHROMADB_CHUNK_OVERLAP = 75
N_CHROMADB_RESULTS = 15
N_CHROMADB_UNIQUE_RESULTS = 3

N_WEB_SEARCH_RESULTS = 3
WEB_SEARCH_SCRAPING_TIMEOUT_SECONDS = 5
WEB_SEARCH_SCRAPING_MAX_RESULT_LENGTH = 10000

SPLIT_DOCUMENTS_LONGER_THAN_N_CHARS = 8000
MIN_SPLIT_LENGTH_CHARS = 2000

WEB_SEARCH_MODEL = "gpt-3.5-turbo"
WEB_SEARCH_SUMMARIZE_MAX_TOKENS = 1000
WEB_SEARCH_TEMPERATURE = 0.7
WEB_SEARCH_MODEL_KWARGS: Mapping[str, Any] = {}

CONVERSATION_SUMMARY_MODEL = "gpt-3.5-turbo"
