DEFAULT_MODEL = "gpt-3.5-turbo"
DEFAULT_TEMPERATURE = 0.7
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_PRESENCE_PENALTY = 0.0
DEFAULT_TOP_P = 1.0

SPLIT_DOCUMENTS_LONGER_THAN_N_CHARS = 8000
MIN_SPLIT_LENGTH_CHARS = 2000
